//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OrderStatus = &struct {
	Delivered postgres.StringExpression
	Shipped   postgres.StringExpression
	Ordered   postgres.StringExpression
	Failed    postgres.StringExpression
	Pending   postgres.StringExpression
}{
	Delivered: postgres.NewEnumValue("Delivered"),
	Shipped:   postgres.NewEnumValue("Shipped"),
	Ordered:   postgres.NewEnumValue("Ordered"),
	Failed:    postgres.NewEnumValue("Failed"),
	Pending:   postgres.NewEnumValue("pending"),
}
