//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuthorBooks = newAuthorBooksTable("public", "author_books", "")

type authorBooksTable struct {
	postgres.Table

	// Columns
	ID       postgres.ColumnInteger
	AuthorID postgres.ColumnString
	BookID   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuthorBooksTable struct {
	authorBooksTable

	EXCLUDED authorBooksTable
}

// AS creates new AuthorBooksTable with assigned alias
func (a AuthorBooksTable) AS(alias string) *AuthorBooksTable {
	return newAuthorBooksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthorBooksTable with assigned schema name
func (a AuthorBooksTable) FromSchema(schemaName string) *AuthorBooksTable {
	return newAuthorBooksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthorBooksTable with assigned table prefix
func (a AuthorBooksTable) WithPrefix(prefix string) *AuthorBooksTable {
	return newAuthorBooksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthorBooksTable with assigned table suffix
func (a AuthorBooksTable) WithSuffix(suffix string) *AuthorBooksTable {
	return newAuthorBooksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthorBooksTable(schemaName, tableName, alias string) *AuthorBooksTable {
	return &AuthorBooksTable{
		authorBooksTable: newAuthorBooksTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newAuthorBooksTableImpl("", "excluded", ""),
	}
}

func newAuthorBooksTableImpl(schemaName, tableName, alias string) authorBooksTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		AuthorIDColumn = postgres.StringColumn("author_id")
		BookIDColumn   = postgres.StringColumn("book_id")
		allColumns     = postgres.ColumnList{IDColumn, AuthorIDColumn, BookIDColumn}
		mutableColumns = postgres.ColumnList{AuthorIDColumn, BookIDColumn}
		defaultColumns = postgres.ColumnList{}
	)

	return authorBooksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		AuthorID: AuthorIDColumn,
		BookID:   BookIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
