//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Books = newBooksTable("public", "books", "")

type booksTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	ProductID       postgres.ColumnString
	Title           postgres.ColumnString
	Author          postgres.ColumnString
	Description     postgres.ColumnString
	Publisher       postgres.ColumnString
	Price           postgres.ColumnFloat
	Tags            postgres.ColumnStringArray
	Language        postgres.ColumnString
	IsFeatured      postgres.ColumnBool
	ImageDirectory  postgres.ColumnString
	PublicationYear postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz
	Edition         postgres.ColumnString
	NumImages       postgres.ColumnInteger
	Condition       postgres.ColumnString
	Stock           postgres.ColumnInteger
	Isbn10          postgres.ColumnString
	Isbn13          postgres.ColumnString
	OmitBy          postgres.ColumnBool // don't include "by" when displaying this book (ie has "by" already in author)

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BooksTable struct {
	booksTable

	EXCLUDED booksTable
}

// AS creates new BooksTable with assigned alias
func (a BooksTable) AS(alias string) *BooksTable {
	return newBooksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BooksTable with assigned schema name
func (a BooksTable) FromSchema(schemaName string) *BooksTable {
	return newBooksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BooksTable with assigned table prefix
func (a BooksTable) WithPrefix(prefix string) *BooksTable {
	return newBooksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BooksTable with assigned table suffix
func (a BooksTable) WithSuffix(suffix string) *BooksTable {
	return newBooksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBooksTable(schemaName, tableName, alias string) *BooksTable {
	return &BooksTable{
		booksTable: newBooksTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newBooksTableImpl("", "excluded", ""),
	}
}

func newBooksTableImpl(schemaName, tableName, alias string) booksTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		ProductIDColumn       = postgres.StringColumn("product_id")
		TitleColumn           = postgres.StringColumn("title")
		AuthorColumn          = postgres.StringColumn("author")
		DescriptionColumn     = postgres.StringColumn("description")
		PublisherColumn       = postgres.StringColumn("publisher")
		PriceColumn           = postgres.FloatColumn("price")
		TagsColumn            = postgres.StringArrayColumn("tags")
		LanguageColumn        = postgres.StringColumn("language")
		IsFeaturedColumn      = postgres.BoolColumn("is_featured")
		ImageDirectoryColumn  = postgres.StringColumn("image_directory")
		PublicationYearColumn = postgres.StringColumn("publication_year")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		EditionColumn         = postgres.StringColumn("edition")
		NumImagesColumn       = postgres.IntegerColumn("num_images")
		ConditionColumn       = postgres.StringColumn("condition")
		StockColumn           = postgres.IntegerColumn("stock")
		Isbn10Column          = postgres.StringColumn("isbn10")
		Isbn13Column          = postgres.StringColumn("isbn13")
		OmitByColumn          = postgres.BoolColumn("omit_by")
		allColumns            = postgres.ColumnList{IDColumn, ProductIDColumn, TitleColumn, AuthorColumn, DescriptionColumn, PublisherColumn, PriceColumn, TagsColumn, LanguageColumn, IsFeaturedColumn, ImageDirectoryColumn, PublicationYearColumn, CreatedAtColumn, EditionColumn, NumImagesColumn, ConditionColumn, StockColumn, Isbn10Column, Isbn13Column, OmitByColumn}
		mutableColumns        = postgres.ColumnList{ProductIDColumn, TitleColumn, AuthorColumn, DescriptionColumn, PublisherColumn, PriceColumn, TagsColumn, LanguageColumn, IsFeaturedColumn, ImageDirectoryColumn, PublicationYearColumn, CreatedAtColumn, EditionColumn, NumImagesColumn, ConditionColumn, StockColumn, Isbn10Column, Isbn13Column, OmitByColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, CreatedAtColumn, NumImagesColumn, StockColumn, OmitByColumn}
	)

	return booksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		ProductID:       ProductIDColumn,
		Title:           TitleColumn,
		Author:          AuthorColumn,
		Description:     DescriptionColumn,
		Publisher:       PublisherColumn,
		Price:           PriceColumn,
		Tags:            TagsColumn,
		Language:        LanguageColumn,
		IsFeatured:      IsFeaturedColumn,
		ImageDirectory:  ImageDirectoryColumn,
		PublicationYear: PublicationYearColumn,
		CreatedAt:       CreatedAtColumn,
		Edition:         EditionColumn,
		NumImages:       NumImagesColumn,
		Condition:       ConditionColumn,
		Stock:           StockColumn,
		Isbn10:          Isbn10Column,
		Isbn13:          Isbn13Column,
		OmitBy:          OmitByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
