//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BooksTag = newBooksTagTable("public", "books_tag", "")

type booksTagTable struct {
	postgres.Table

	// Columns
	ID     postgres.ColumnInteger
	BookID postgres.ColumnString
	TagID  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BooksTagTable struct {
	booksTagTable

	EXCLUDED booksTagTable
}

// AS creates new BooksTagTable with assigned alias
func (a BooksTagTable) AS(alias string) *BooksTagTable {
	return newBooksTagTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BooksTagTable with assigned schema name
func (a BooksTagTable) FromSchema(schemaName string) *BooksTagTable {
	return newBooksTagTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BooksTagTable with assigned table prefix
func (a BooksTagTable) WithPrefix(prefix string) *BooksTagTable {
	return newBooksTagTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BooksTagTable with assigned table suffix
func (a BooksTagTable) WithSuffix(suffix string) *BooksTagTable {
	return newBooksTagTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBooksTagTable(schemaName, tableName, alias string) *BooksTagTable {
	return &BooksTagTable{
		booksTagTable: newBooksTagTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newBooksTagTableImpl("", "excluded", ""),
	}
}

func newBooksTagTableImpl(schemaName, tableName, alias string) booksTagTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		BookIDColumn   = postgres.StringColumn("book_id")
		TagIDColumn    = postgres.StringColumn("tag_id")
		allColumns     = postgres.ColumnList{IDColumn, BookIDColumn, TagIDColumn}
		mutableColumns = postgres.ColumnList{BookIDColumn, TagIDColumn}
		defaultColumns = postgres.ColumnList{}
	)

	return booksTagTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:     IDColumn,
		BookID: BookIDColumn,
		TagID:  TagIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
