//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CartItems = newCartItemsTable("public", "cart_items", "")

type cartItemsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	CartID    postgres.ColumnString
	BookID    postgres.ColumnString
	Quantity  postgres.ColumnInteger
	ProductID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CartItemsTable struct {
	cartItemsTable

	EXCLUDED cartItemsTable
}

// AS creates new CartItemsTable with assigned alias
func (a CartItemsTable) AS(alias string) *CartItemsTable {
	return newCartItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CartItemsTable with assigned schema name
func (a CartItemsTable) FromSchema(schemaName string) *CartItemsTable {
	return newCartItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CartItemsTable with assigned table prefix
func (a CartItemsTable) WithPrefix(prefix string) *CartItemsTable {
	return newCartItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CartItemsTable with assigned table suffix
func (a CartItemsTable) WithSuffix(suffix string) *CartItemsTable {
	return newCartItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCartItemsTable(schemaName, tableName, alias string) *CartItemsTable {
	return &CartItemsTable{
		cartItemsTable: newCartItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCartItemsTableImpl("", "excluded", ""),
	}
}

func newCartItemsTableImpl(schemaName, tableName, alias string) cartItemsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		CartIDColumn    = postgres.StringColumn("cart_id")
		BookIDColumn    = postgres.StringColumn("book_id")
		QuantityColumn  = postgres.IntegerColumn("quantity")
		ProductIDColumn = postgres.StringColumn("product_id")
		allColumns      = postgres.ColumnList{IDColumn, CartIDColumn, BookIDColumn, QuantityColumn, ProductIDColumn}
		mutableColumns  = postgres.ColumnList{CartIDColumn, BookIDColumn, QuantityColumn, ProductIDColumn}
		defaultColumns  = postgres.ColumnList{IDColumn}
	)

	return cartItemsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CartID:    CartIDColumn,
		BookID:    BookIDColumn,
		Quantity:  QuantityColumn,
		ProductID: ProductIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
