//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CollectionItems = newCollectionItemsTable("public", "collection_items", "")

type collectionItemsTable struct {
	postgres.Table

	// Columns
	BookID       postgres.ColumnString
	CollectionID postgres.ColumnString
	ID           postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CollectionItemsTable struct {
	collectionItemsTable

	EXCLUDED collectionItemsTable
}

// AS creates new CollectionItemsTable with assigned alias
func (a CollectionItemsTable) AS(alias string) *CollectionItemsTable {
	return newCollectionItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CollectionItemsTable with assigned schema name
func (a CollectionItemsTable) FromSchema(schemaName string) *CollectionItemsTable {
	return newCollectionItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CollectionItemsTable with assigned table prefix
func (a CollectionItemsTable) WithPrefix(prefix string) *CollectionItemsTable {
	return newCollectionItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CollectionItemsTable with assigned table suffix
func (a CollectionItemsTable) WithSuffix(suffix string) *CollectionItemsTable {
	return newCollectionItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCollectionItemsTable(schemaName, tableName, alias string) *CollectionItemsTable {
	return &CollectionItemsTable{
		collectionItemsTable: newCollectionItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newCollectionItemsTableImpl("", "excluded", ""),
	}
}

func newCollectionItemsTableImpl(schemaName, tableName, alias string) collectionItemsTable {
	var (
		BookIDColumn       = postgres.StringColumn("book_id")
		CollectionIDColumn = postgres.StringColumn("collection_id")
		IDColumn           = postgres.StringColumn("id")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{BookIDColumn, CollectionIDColumn, IDColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{BookIDColumn, CollectionIDColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return collectionItemsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		BookID:       BookIDColumn,
		CollectionID: CollectionIDColumn,
		ID:           IDColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
