//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Collections = newCollectionsTable("public", "collections", "")

// groups of books
type collectionsTable struct {
	postgres.Table

	// Columns
	CreatedAt   postgres.ColumnTimestampz
	Title       postgres.ColumnString
	Description postgres.ColumnString
	Active      postgres.ColumnBool
	ID          postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CollectionsTable struct {
	collectionsTable

	EXCLUDED collectionsTable
}

// AS creates new CollectionsTable with assigned alias
func (a CollectionsTable) AS(alias string) *CollectionsTable {
	return newCollectionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CollectionsTable with assigned schema name
func (a CollectionsTable) FromSchema(schemaName string) *CollectionsTable {
	return newCollectionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CollectionsTable with assigned table prefix
func (a CollectionsTable) WithPrefix(prefix string) *CollectionsTable {
	return newCollectionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CollectionsTable with assigned table suffix
func (a CollectionsTable) WithSuffix(suffix string) *CollectionsTable {
	return newCollectionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCollectionsTable(schemaName, tableName, alias string) *CollectionsTable {
	return &CollectionsTable{
		collectionsTable: newCollectionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCollectionsTableImpl("", "excluded", ""),
	}
}

func newCollectionsTableImpl(schemaName, tableName, alias string) collectionsTable {
	var (
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		TitleColumn       = postgres.StringColumn("title")
		DescriptionColumn = postgres.StringColumn("description")
		ActiveColumn      = postgres.BoolColumn("active")
		IDColumn          = postgres.StringColumn("id")
		allColumns        = postgres.ColumnList{CreatedAtColumn, TitleColumn, DescriptionColumn, ActiveColumn, IDColumn}
		mutableColumns    = postgres.ColumnList{CreatedAtColumn, TitleColumn, DescriptionColumn, ActiveColumn}
		defaultColumns    = postgres.ColumnList{CreatedAtColumn, IDColumn}
	)

	return collectionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		CreatedAt:   CreatedAtColumn,
		Title:       TitleColumn,
		Description: DescriptionColumn,
		Active:      ActiveColumn,
		ID:          IDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
