//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Orders = newOrdersTable("public", "orders", "")

type ordersTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnString
	UserID           postgres.ColumnString
	OrderedAt        postgres.ColumnTimestampz
	Status           postgres.ColumnString
	SessionID        postgres.ColumnString
	ItemsTotal       postgres.ColumnFloat
	ShippingCost     postgres.ColumnFloat
	Address          postgres.ColumnString
	TrackingNumber   postgres.ColumnString
	ShippingProvider postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OrdersTable struct {
	ordersTable

	EXCLUDED ordersTable
}

// AS creates new OrdersTable with assigned alias
func (a OrdersTable) AS(alias string) *OrdersTable {
	return newOrdersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrdersTable with assigned schema name
func (a OrdersTable) FromSchema(schemaName string) *OrdersTable {
	return newOrdersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrdersTable with assigned table prefix
func (a OrdersTable) WithPrefix(prefix string) *OrdersTable {
	return newOrdersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrdersTable with assigned table suffix
func (a OrdersTable) WithSuffix(suffix string) *OrdersTable {
	return newOrdersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrdersTable(schemaName, tableName, alias string) *OrdersTable {
	return &OrdersTable{
		ordersTable: newOrdersTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newOrdersTableImpl("", "excluded", ""),
	}
}

func newOrdersTableImpl(schemaName, tableName, alias string) ordersTable {
	var (
		IDColumn               = postgres.StringColumn("id")
		UserIDColumn           = postgres.StringColumn("user_id")
		OrderedAtColumn        = postgres.TimestampzColumn("ordered_at")
		StatusColumn           = postgres.StringColumn("status")
		SessionIDColumn        = postgres.StringColumn("session_id")
		ItemsTotalColumn       = postgres.FloatColumn("items_total")
		ShippingCostColumn     = postgres.FloatColumn("shipping_cost")
		AddressColumn          = postgres.StringColumn("address")
		TrackingNumberColumn   = postgres.StringColumn("tracking_number")
		ShippingProviderColumn = postgres.StringColumn("shipping_provider")
		allColumns             = postgres.ColumnList{IDColumn, UserIDColumn, OrderedAtColumn, StatusColumn, SessionIDColumn, ItemsTotalColumn, ShippingCostColumn, AddressColumn, TrackingNumberColumn, ShippingProviderColumn}
		mutableColumns         = postgres.ColumnList{UserIDColumn, OrderedAtColumn, StatusColumn, SessionIDColumn, ItemsTotalColumn, ShippingCostColumn, AddressColumn, TrackingNumberColumn, ShippingProviderColumn}
		defaultColumns         = postgres.ColumnList{IDColumn, OrderedAtColumn}
	)

	return ordersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		UserID:           UserIDColumn,
		OrderedAt:        OrderedAtColumn,
		Status:           StatusColumn,
		SessionID:        SessionIDColumn,
		ItemsTotal:       ItemsTotalColumn,
		ShippingCost:     ShippingCostColumn,
		Address:          AddressColumn,
		TrackingNumber:   TrackingNumberColumn,
		ShippingProvider: ShippingProviderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
