//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OrderItems = newOrderItemsTable("public", "order_items", "")

type orderItemsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrderID        postgres.ColumnString
	BookID         postgres.ColumnString
	Quantity       postgres.ColumnInteger
	Price          postgres.ColumnFloat
	ProductID      postgres.ColumnString
	BookTitle      postgres.ColumnString
	BookAuthor     postgres.ColumnString
	ImageDirectory postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OrderItemsTable struct {
	orderItemsTable

	EXCLUDED orderItemsTable
}

// AS creates new OrderItemsTable with assigned alias
func (a OrderItemsTable) AS(alias string) *OrderItemsTable {
	return newOrderItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrderItemsTable with assigned schema name
func (a OrderItemsTable) FromSchema(schemaName string) *OrderItemsTable {
	return newOrderItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrderItemsTable with assigned table prefix
func (a OrderItemsTable) WithPrefix(prefix string) *OrderItemsTable {
	return newOrderItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrderItemsTable with assigned table suffix
func (a OrderItemsTable) WithSuffix(suffix string) *OrderItemsTable {
	return newOrderItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrderItemsTable(schemaName, tableName, alias string) *OrderItemsTable {
	return &OrderItemsTable{
		orderItemsTable: newOrderItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newOrderItemsTableImpl("", "excluded", ""),
	}
}

func newOrderItemsTableImpl(schemaName, tableName, alias string) orderItemsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrderIDColumn        = postgres.StringColumn("order_id")
		BookIDColumn         = postgres.StringColumn("book_id")
		QuantityColumn       = postgres.IntegerColumn("quantity")
		PriceColumn          = postgres.FloatColumn("price")
		ProductIDColumn      = postgres.StringColumn("product_id")
		BookTitleColumn      = postgres.StringColumn("book_title")
		BookAuthorColumn     = postgres.StringColumn("book_author")
		ImageDirectoryColumn = postgres.StringColumn("image_directory")
		allColumns           = postgres.ColumnList{IDColumn, OrderIDColumn, BookIDColumn, QuantityColumn, PriceColumn, ProductIDColumn, BookTitleColumn, BookAuthorColumn, ImageDirectoryColumn}
		mutableColumns       = postgres.ColumnList{OrderIDColumn, BookIDColumn, QuantityColumn, PriceColumn, ProductIDColumn, BookTitleColumn, BookAuthorColumn, ImageDirectoryColumn}
		defaultColumns       = postgres.ColumnList{IDColumn}
	)

	return orderItemsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrderID:        OrderIDColumn,
		BookID:         BookIDColumn,
		Quantity:       QuantityColumn,
		Price:          PriceColumn,
		ProductID:      ProductIDColumn,
		BookTitle:      BookTitleColumn,
		BookAuthor:     BookAuthorColumn,
		ImageDirectory: ImageDirectoryColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
