//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Prices = newPricesTable("public", "prices", "")

type pricesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	ProductID   postgres.ColumnString
	Active      postgres.ColumnBool
	Description postgres.ColumnString
	UnitAmount  postgres.ColumnFloat
	Currency    postgres.ColumnString
	Type        postgres.ColumnString
	Metadata    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PricesTable struct {
	pricesTable

	EXCLUDED pricesTable
}

// AS creates new PricesTable with assigned alias
func (a PricesTable) AS(alias string) *PricesTable {
	return newPricesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PricesTable with assigned schema name
func (a PricesTable) FromSchema(schemaName string) *PricesTable {
	return newPricesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PricesTable with assigned table prefix
func (a PricesTable) WithPrefix(prefix string) *PricesTable {
	return newPricesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PricesTable with assigned table suffix
func (a PricesTable) WithSuffix(suffix string) *PricesTable {
	return newPricesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPricesTable(schemaName, tableName, alias string) *PricesTable {
	return &PricesTable{
		pricesTable: newPricesTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newPricesTableImpl("", "excluded", ""),
	}
}

func newPricesTableImpl(schemaName, tableName, alias string) pricesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		ProductIDColumn   = postgres.StringColumn("product_id")
		ActiveColumn      = postgres.BoolColumn("active")
		DescriptionColumn = postgres.StringColumn("description")
		UnitAmountColumn  = postgres.FloatColumn("unit_amount")
		CurrencyColumn    = postgres.StringColumn("currency")
		TypeColumn        = postgres.StringColumn("type")
		MetadataColumn    = postgres.StringColumn("metadata")
		allColumns        = postgres.ColumnList{IDColumn, ProductIDColumn, ActiveColumn, DescriptionColumn, UnitAmountColumn, CurrencyColumn, TypeColumn, MetadataColumn}
		mutableColumns    = postgres.ColumnList{ProductIDColumn, ActiveColumn, DescriptionColumn, UnitAmountColumn, CurrencyColumn, TypeColumn, MetadataColumn}
		defaultColumns    = postgres.ColumnList{}
	)

	return pricesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		ProductID:   ProductIDColumn,
		Active:      ActiveColumn,
		Description: DescriptionColumn,
		UnitAmount:  UnitAmountColumn,
		Currency:    CurrencyColumn,
		Type:        TypeColumn,
		Metadata:    MetadataColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
