//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type Books struct {
	ID              uuid.UUID `sql:"primary_key"`
	ProductID       *string
	Title           string
	Author          string
	Description     *string
	Publisher       *string
	Price           float64
	Tags            *pq.StringArray
	Language        *string
	IsFeatured      *bool
	ImageDirectory  *string
	PublicationYear *string
	CreatedAt       *time.Time
	Edition         *string
	NumImages       *int32
	Condition       *string
	Stock           int32
	Isbn10          *string
	Isbn13          *string
	OmitBy          *bool // don't include "by" when displaying this book (ie has "by" already in author)
}
