//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type CartItems struct {
	ID        uuid.UUID `sql:"primary_key"`
	CartID    uuid.UUID
	BookID    uuid.UUID
	Quantity  int32
	ProductID *string
}
