//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

// groups of books
type Collections struct {
	CreatedAt   time.Time
	Title       *string
	Description *string
	Active      *bool
	ID          uuid.UUID `sql:"primary_key"`
}
