//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type CollectionItems struct {
	BookID       uuid.UUID
	CollectionID uuid.UUID
	ID           uuid.UUID `sql:"primary_key"`
	CreatedAt    *time.Time
}
