//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OrderStatus string

const (
	OrderStatus_Delivered OrderStatus = "Delivered"
	OrderStatus_Shipped   OrderStatus = "Shipped"
	OrderStatus_Ordered   OrderStatus = "Ordered"
	OrderStatus_Failed    OrderStatus = "Failed"
	OrderStatus_Pending   OrderStatus = "pending"
)

var OrderStatusAllValues = []OrderStatus{
	OrderStatus_Delivered,
	OrderStatus_Shipped,
	OrderStatus_Ordered,
	OrderStatus_Failed,
	OrderStatus_Pending,
}

func (e *OrderStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Delivered":
		*e = OrderStatus_Delivered
	case "Shipped":
		*e = OrderStatus_Shipped
	case "Ordered":
		*e = OrderStatus_Ordered
	case "Failed":
		*e = OrderStatus_Failed
	case "pending":
		*e = OrderStatus_Pending
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OrderStatus enum")
	}

	return nil
}

func (e OrderStatus) String() string {
	return string(e)
}
