//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Orders struct {
	ID               uuid.UUID `sql:"primary_key"`
	UserID           uuid.UUID
	OrderedAt        time.Time
	Status           *OrderStatus
	SessionID        *string
	ItemsTotal       *float64
	ShippingCost     *float64
	Address          *string
	TrackingNumber   *string
	ShippingProvider *string
}
