//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type OrderItems struct {
	ID             uuid.UUID `sql:"primary_key"`
	OrderID        uuid.UUID
	BookID         uuid.UUID
	Quantity       int32
	Price          float64
	ProductID      *string
	BookTitle      *string
	BookAuthor     *string
	ImageDirectory *string
}
