//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Prices struct {
	ID          string `sql:"primary_key"`
	ProductID   *string
	Active      *bool
	Description *string
	UnitAmount  *float64
	Currency    *string
	Type        *PricingType
	Metadata    *string
}
