//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PricingType string

const (
	PricingType_OneTime PricingType = "one_time"
)

var PricingTypeAllValues = []PricingType{
	PricingType_OneTime,
}

func (e *PricingType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "one_time":
		*e = PricingType_OneTime
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PricingType enum")
	}

	return nil
}

func (e PricingType) String() string {
	return string(e)
}
