//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type Products struct {
	ID          string `sql:"primary_key"`
	Active      *bool
	Name        *string
	Description *string
	Image       *string
	Metadata    *string
	BookID      *uuid.UUID
}
